{{ config(materialized='table') }}

SELECT
    CUSTOMER_ID,
    COUNT(DISTINCT POLICY_ID) AS TOTAL_POLICIES,
    SUM(PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
    SUM(TOTAL_CLAIMS) AS TOTAL_CLAIMS,
    SUM(TOTAL_PAYMENTS) AS TOTAL_PAYMENTS,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM {{ ref('gold_policy_summary') }}
GROUP BY CUSTOMER_ID